### ISSUE TITLE
Missing playerHandler.addClient() function causes players to never disconnect.

### ISSUE THREAD

**Issue by Maxetto** [Luka967/Ogar#2]
I have this problem since last "release" update where players doesn't disconnect after they left the server, causing the server to get full and consume free resources.

I've then decided to update to this "dev" branch, and you seem to have missed the "this.playerHandler.addClient(ws);" line in GameServer.js when you reverted back to syncronized ticking and updating.

I'm asking you there because I'll greatly appreciate a quick fix.
Thank You.

Full StackTrace:
>TypeError: undefined is not a function
    at GameServer.connectionEstablished (/root/ogar/src/GameServer.js:257:28)
    at WebSocketServer.emit (events.js:107:17)
    at /root/ogar/node_modules/ws/lib/WebSocketServer.js:91:14
    at completeHybiUpgrade2 (/root/ogar/node_modules/ws/lib/WebSocketServer.js:284:5)
    at completeHybiUpgrade1 (/root/ogar/node_modules/ws/lib/WebSocketServer.js:309:13)
    at WebSocketServer.handleHybiUpgrade (/root/ogar/node_modules/ws/lib/WebSocketServer.js:337:3)
    at WebSocketServer.handleUpgrade (/root/ogar/node_modules/ws/lib/WebSocketServer.js:173:26)
    at Server.WebSocketServer._onServerUpgrade (/root/ogar/node_modules/ws/lib/WebSocketServer.js:89:12)
    at Server.emit (events.js:118:17)
    at Socket.socketOnData (_http_server.js:368:14)

**Comment by Luka967** [comment]
I did all the stuff and also some optimizations (again).
I'll commit it all now.

**Comment by Maxetto** [comment]
(Auto-)Updated and Fixed!

Thank you.

**Comment by Luka967** [comment]
Oh and I forgot to ask one thing, what is the IP for the server? I'd like to take a look at it :3

**Comment by Maxetto** [comment]
It's nothing special. Just a Vanilla Empty Italian Server :stuck_out_tongue: 

But if you really want to see it, it's: agar.maxcraft.it:30065

**Comment by Luka967** [comment]
Thank you. I'm asking because players on my private server told me that there is a lot of lag while playing. Just wanted to try it out on your server, and it looks a bit choppy, so I'll need to see what's happening there.
